Fix pre-commit script to use nightly rustfmt.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,15 +3,29 @@
 HAS_ISSUES=0
 FIRST_FILE=1
 
+RUSTUP=`which rustup`
+if [[ ! -x $RUSTUP  ]]; then
+    echo "Rustup is needed for nightly rustfmt; cannot commit."
+    exit 1
+fi
+
+RUSTFMT=`rustup which --toolchain nightly rustfmt`
+if [[ ! -x $RUSTFMT ]]; then
+    echo "Error finding nightly version of rustfmt; cannot commit."
+    exit 1
+fi
+pat='.*\.rs$'
 for file in $(git diff --name-only --staged); do
-    FMT_RESULT="$(rustfmt --check $file 2>/dev/null || true)"
-    if [ "$FMT_RESULT" != "" ]; then
-        if [ $FIRST_FILE -eq 0 ]; then
-            echo -n ", "
+    if [[ $file =~ $pat ]]; then
+        FMT_RESULT="$($RUSTFMT --check $file)"
+        if [[ $? != 0 || "$FMT_RESULT" != "" ]]; then
+            if [ $FIRST_FILE -eq 0 ]; then
+                echo -n ", "
+            fi
+            echo -n "$file"
+            HAS_ISSUES=1
+            FIRST_FILE=0
         fi
-        echo -n "$file"
-        HAS_ISSUES=1
-        FIRST_FILE=0
     fi
 done
 
